name: accounting_notebook
description: Interactive accounting notebook for students
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_quill: ^9.0.0
  shared_preferences: ^2.2.0
  path: ^1.8.3
  file_picker: ^6.0.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  uuid: ^4.0.0
  collection: ^1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
