name: accounting_notebook
description: Interactive accounting notebook for students
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

  flutter_quill: ^9.3.11
  shared_preferences: ^2.3.3
  path: ^1.9.0
  file_picker: ^8.0.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  uuid: ^4.5.1
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
